# Generated by Django 3.2.7 on 2021-09-14 13:50

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.auth.management import create_permissions

def populate_groups(apps, schema_editor):
    user_roles = ['User manager', 'Maintainer', 
                'Contributor', 'Read only']
    for name in user_roles:
        Group.objects.create(name=name)

    # Create permissions before trying to apply them
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

     # Assign model-level permissions to each group
    # TODO: Check these are the correct permissions 
    all_perms = Permission.objects.all()
    data_apps = ['battDB', 'common', 'dfndb']

    user_manager_perms = [i for i in all_perms
                            if i.content_type.app_label in ['management']]
    Group.objects.get(name='User manager').permissions.add(*user_manager_perms)
    # Maintainers have access to "data apps" only (no user-related stuff)
    maintainer_perms = [i for i in all_perms 
                        if i.content_type.app_label in data_apps]
    Group.objects.get(name='Maintainer').permissions.add(*maintainer_perms)
    # Contributors can view, add and change
    # TODO: This should be more granular e.g. can only change their own items
    #       and can only view "published" items of other people. 
    contrib_perms = [i for i in maintainer_perms 
                    if i.codename.split('_')[0] in ['view', 'add', 'change']]
    Group.objects.get(name='Contributor').permissions.add(*contrib_perms)               
    # Read only users
    read_perms = [i for i in maintainer_perms 
                    if i.codename.split('_')[0] in ['view']]
    Group.objects.get(name='Read only').permissions.add(*read_perms) 

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('battDB', '0003_initial'),
        ('common', '0002_initial'),
        ('dfndb', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_groups)
    ]
