# Generated by Django 3.2.7 on 2021-09-14 13:50

from django.db import migrations
from ..initial_data import populate_groups


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("battDB", "0003_initial"),
        ("common", "0002_initial"),
        ("dfndb", "0002_initial"),
    ]

    operations = [migrations.RunPython(populate_groups)]
