# Generated by Django 3.2.7 on 2021-09-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battDB', '0001_initial'),
        ('dfndb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.parameter'),
        ),
        migrations.AddField(
            model_name='signaltype',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='battDB.parser'),
        ),
        migrations.AddField(
            model_name='parser',
            name='parameters',
            field=models.ManyToManyField(through='battDB.SignalType', to='dfndb.Parameter'),
        ),
    ]
