# Generated by Django 3.2.8 on 2021-10-18 19:39

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0002_alter_parser_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files', validators=[common.validators.validate_data_file]),
        ),
    ]
