# Generated by Django 3.2.8 on 2021-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0002_auto_20211006_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='parser',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
    ]
