# Generated by Django 3.2.8 on 2021-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='file_format',
            field=models.CharField(choices=[('Dummy', 'Dummy parser that does nothing'), ('biologic', 'Biologic CSV/TSV/MPT'), ('maccor', 'Maccor XLS/XLSX')], default=('Dummy', 'Dummy parser that does nothing'), help_text='File format', max_length=50),
        ),
    ]
