# Generated by Django 2.2.14 on 2020-08-04 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import battDB.models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0004_equipmenttype_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="cellbatch",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="cellseparator",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.equipmentType_schema
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="experimentalapparatus",
            name="cellConfig",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="experimentalapparatus",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="signaltype",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="testprotocol",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
