# Generated by Django 3.2.7 on 2021-10-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0004_alter_parser_file_format'),
        ('battDB', '0004_auto_20211015_1354'),
    ]

    operations = [
    ]
