# Generated by Django 3.2.7 on 2021-10-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battDB', '0004_auto_20211014_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparameter',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
        migrations.AddField(
            model_name='deviceparameter',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
