# Generated by Django 3.2.7 on 2021-11-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0005_merge_20211022_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicespecification',
            name='abstract',
            field=models.BooleanField(default=False, help_text="\n        This specifies an abstract device, e.g. 'Cell' with child members\n        such as 'Positive Electrode, Negative Electrode, Electrolyte etc.\n        If this is set to True, then all metadata declared here must be\n        overridden in child classes. An abstract specification cannot be used\n        to define a physical device or batch.\n        ", verbose_name='Abstract Specification'),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Device type. e.g. Cell, Module, Battery Pack. An abstract\n        specification cannot have a device type -  they define the device types.', limit_choices_to={'abstract': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifies', to='battDB.devicespecification'),
        ),
    ]
