# Generated by Django 3.2.9 on 2021-11-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0008_remove_experiment_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='manufacturer',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='specification',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNo',
            field=models.CharField(blank=True, default='', help_text='Serial number, if any, for this piece of equipment', max_length=60),
        ),
    ]
