# Generated by Django 2.2.14 on 2020-08-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0008_experimentalapparatus_cellconfig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experiment", old_name="data_file", new_name="raw_data_file",
        ),
    ]
