# Generated by Django 3.2.9 on 2021-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0009_auto_20211117_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='serialNo',
            field=models.CharField(blank=True, default='20211206-155605', help_text='Batch number, optionally indicate serial number format', max_length=60),
        ),
    ]
