# Generated by Django 3.2.9 on 2021-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0010_alter_batch_serialno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='serialNo',
            field=models.CharField(blank=True, default='20211206-155801', help_text='Batch number, default is date-time stamp', max_length=60),
        ),
    ]
