# Generated by Django 2.2.14 on 2020-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0013_auto_20200805_1146"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="experiment", name="unique_namestring",),
        migrations.AlterField(
            model_name="experiment",
            name="name",
            field=models.SlugField(default="experiment"),
        ),
        migrations.AddConstraint(
            model_name="experiment",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "date"), name="unique_namestring"
            ),
        ),
    ]
