# Generated by Django 2.2.14 on 2020-08-12 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import battDB.models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0014_auto_20200805_1214"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "raw_data_file",
                    models.FileField(null=True, upload_to="raw_data_files"),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=battDB.models.resultMetadata_schema
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveConstraint(model_name="experiment", name="unique_namestring",),
        migrations.RemoveField(model_name="experiment", name="processed_data_file",),
        migrations.RemoveField(model_name="experiment", name="raw_data_file",),
        migrations.AlterField(
            model_name="experiment", name="name", field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="experiment",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "date"), name="unique_slugname"
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="results",
            field=models.ManyToManyField(to="battDB.ExperimentResult"),
        ),
    ]
