# Generated by Django 2.2.14 on 2020-08-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0015_auto_20200812_1541"),
    ]

    operations = [
        migrations.RemoveField(model_name="experimentresult", name="attributes",),
        migrations.RemoveField(model_name="experimentresult", name="name",),
    ]
