# Generated by Django 4.0.2 on 2022-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0016_alter_devicespecification_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='file_format',
            field=models.CharField(choices=[('Dummy', 'Dummy parsing engine that does nothing'), ('biologic', 'Biologic CSV/TSV/MPT'), ('maccor', 'Maccor XLS/XLSX')], default=('Dummy', 'Dummy parsing engine that does nothing'), help_text='File format', max_length=100),
        ),
    ]
