# Generated by Django 4.0.2 on 2022-02-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0017_alter_parser_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicespecification',
            name='config',
            field=models.ForeignKey(blank=True, help_text='Configuration of subdevices if the device type is a module or pack.', limit_choices_to={'config_type': 'module'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_modules', to='battDB.deviceconfig', verbose_name='Configuration'),
        ),
    ]
