# Generated by Django 4.0.2 on 2022-02-17 14:33

from django.db import migrations

from ..initial_parsers import populate_parsers


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0018_alter_devicespecification_config"),
        ("dfndb", "0009_add_new_parameters"),
    ]

    operations = [migrations.RunPython(populate_parsers)]
