# Generated by Django 4.0.2 on 2022-02-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0009_rename_material_compositionpart_component_and_more'),
        ('battDB', '0018_alter_devicespecification_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceparameter',
            old_name='material',
            new_name='component',
        ),
        migrations.AlterUniqueTogether(
            name='deviceparameter',
            unique_together={('spec', 'name'), ('spec', 'parameter', 'component')},
        ),
    ]
