# Generated by Django 2.2.14 on 2020-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0019_auto_20200812_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiment",
            name="cells",
            field=models.ManyToManyField(related_name="experiments", to="battDB.Cell"),
        ),
    ]
