# Generated by Django 4.0.2 on 2022-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0019_initial_parsers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='file_format',
            field=models.CharField(choices=[('Dummy', 'Dummy parsing engine that does nothing'), ('Biologic', 'Biologic CSV/TSV/MPT'), ('Maccor', 'Maccor XLS/XLSX')], default=('Dummy', 'Dummy parsing engine that does nothing'), help_text='File format', max_length=100),
        ),
    ]
