# Generated by Django 3.2.7 on 2022-02-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0019_rename_material_deviceparameter_component_and_more'),
        ('battDB', '0020_alter_parser_file_format'),
    ]

    operations = [
    ]
