# Generated by Django 2.2.14 on 2020-08-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0020_auto_20200812_1646"),
    ]

    operations = [
        migrations.RemoveField(model_name="experiment", name="results",),
        migrations.AddField(
            model_name="experimentresult",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="battDB.Experiment",
            ),
        ),
    ]
