# Generated by Django 4.0.2 on 2022-02-24 11:23

import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0021_merge_20220218_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='specification',
            field=models.ForeignKey(help_text='Type of device in this batch', limit_choices_to={'abstract': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.devicespecification'),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='config',
            field=models.ForeignKey(blank=True, help_text='Leave blank unless this is a new module or pack with a certain configuration', limit_choices_to={'config_type': 'module'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_modules', to='battDB.deviceconfig', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='spec_file',
            field=models.FileField(blank=True, help_text='PDF version of spec. sheet for this type of device', null=True, upload_to='uploaded_files', validators=[common.validators.validate_pdf_file], verbose_name='Specification sheet'),
        ),
        migrations.AlterField(
            model_name='experimentdevice',
            name='device_position',
            field=models.CharField(default='cell_1', help_text='Device Position ID in Experiment Config - e.g. Cell_A1 for the first cell of a series-parallel pack (leave as cell_1 for single cell experiments)', max_length=20),
        ),
    ]
