# Generated by Django 2.2.14 on 2020-08-15 14:26

import battDB.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0021_auto_20200813_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data_file', models.FileField(null=True, upload_to='raw_data_files')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.resultMetadata_schema)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='battDB.Experiment')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperimentResult',
        ),
    ]
