# Generated by Django 2.2.14 on 2020-08-15 16:11

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import battDB.models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0023_experimentdata_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experimentdata",
            options={"verbose_name_plural": "Experiment Data Files"},
        ),
        migrations.RemoveField(model_name="experimentalapparatus", name="protocol",),
        migrations.AddField(
            model_name="experiment",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.TestProtocol",
            ),
        ),
        migrations.AddField(
            model_name="experimentdata",
            name="analysis",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.experimentAnalysis_schema
            ),
        ),
        migrations.AddField(
            model_name="experimentdata",
            name="import_columns",
            field=models.ManyToManyField(blank=True, to="battDB.SignalType"),
        ),
        migrations.AddField(
            model_name="experimentdata",
            name="parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.experimentParameters_schema
            ),
        ),
        migrations.AlterField(
            model_name="experimentdata",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.resultData_schema, editable=False
            ),
        ),
    ]
