# Generated by Django 4.1 on 2022-08-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0011_alter_component_polymer'),
        ('battDB', '0024_additional_exp_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceparameter',
            unique_together={('spec', 'name'), ('spec', 'parameter')},
        ),
        migrations.RemoveField(
            model_name='deviceparameter',
            name='component',
        ),
    ]
