# Generated by Django 2.2.14 on 2020-08-16 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0026_ec_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_cycle',
            name='ts_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ec_cycle',
            name='ts_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), blank=True, null=True, size=None),
        ),
    ]
