# Generated by Django 2.2.14 on 2020-08-16 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import battDB.models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0027_auto_20200816_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdata",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.resultData_schema
            ),
        ),
    ]
