# Generated by Django 2.2.14 on 2020-08-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0028_experimentdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdata',
            name='data',
        ),
    ]
