# Generated by Django 2.2.14 on 2020-08-16 13:57

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0030_experimentdata_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ec_cycle",
            options={
                "verbose_name": "EChem Cycle",
                "verbose_name_plural": "EChem Cycles",
            },
        ),
        migrations.AddField(
            model_name="ec_cycle",
            name="dataFile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cycles",
                to="battDB.ExperimentData",
            ),
        ),
        migrations.AddField(
            model_name="ec_cycle",
            name="events",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
