# Generated by Django 4.1.3 on 2022-11-21 11:55

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0030_experiment_external_link_experiment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='binary_file',
            field=models.FileField(blank=True, help_text='Binary file version of this data output by the cycler', null=True, upload_to='uploaded_files', validators=[common.validators.validate_binary_file], verbose_name='Binary file'),
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='settings_file',
            field=models.FileField(blank=True, help_text='Input settings file for the cycler used to produce this data', null=True, upload_to='uploaded_files', validators=[common.validators.validate_settings_file], verbose_name='Settings file'),
        ),
    ]
