# Generated by Django 2.2.14 on 2020-08-16 14:32

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import battDB.models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0031_auto_20200816_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=battDB.models.cell_schema
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="cell", name="separator",),
        migrations.RemoveField(model_name="experimentalapparatus", name="cellConfig",),
        migrations.AddField(
            model_name="cellconfig",
            name="num_cells",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ec_cycle",
            name="analysis",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.experimentAnalysis_schema
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="cellConfig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.CellConfig",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.cell_schema
            ),
        ),
        migrations.AlterField(
            model_name="cellbatch",
            name="attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=battDB.models.cell_schema
            ),
        ),
        migrations.DeleteModel(name="CellSeparator",),
        migrations.AddField(
            model_name="cell",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.CellType",
            ),
        ),
    ]
