# Generated by Django 4.1.3 on 2022-11-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0031_experimentdatafile_binary_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicespecification',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parser',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
