# Generated by Django 4.1.3 on 2022-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0031_experimentdatafile_binary_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentdevice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='experimentdevice',
            name='data_file',
        ),
    ]
