# Generated by Django 4.1.3 on 2022-12-08 15:07

from django.db import migrations

from battDB.initial_parsers import separate_biologic_parser, update_parser_file_formats


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0032_alter_devicespecification_name_alter_equipment_name_and_more"),
    ]

    operations = [
        migrations.RunPython(update_parser_file_formats),
        migrations.RunPython(separate_biologic_parser),
    ]
