# Generated by Django 2.2.14 on 2020-08-18 13:55

import battDB.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0032_auto_20200816_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, null=True)),
                ('protocol_step', models.PositiveIntegerField()),
                ('step_action', models.CharField(choices=[('chg', 'Charging'), ('dchg', 'Discharging'), ('rest', 'Rest'), (None, 'Undefined')], max_length=8, null=True)),
                ('ts_headers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), blank=True, null=True, size=None)),
                ('ts_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None), blank=True, null=True, size=None)),
                ('events', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.experimentAnalysis_schema)),
            ],
            options={
                'verbose_name_plural': 'Data Ranges',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data_file', models.FileField(null=True, upload_to='raw_data_files')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.resultMetadata_schema)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.resultData_schema)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.experimentParameters_schema)),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.experimentAnalysis_schema)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file', to='battDB.Experiment')),
                ('import_columns', models.ManyToManyField(blank=True, to='battDB.SignalType')),
            ],
            options={
                'verbose_name_plural': 'Experiment Data Files',
            },
        ),
        migrations.RemoveField(
            model_name='experimentdata',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experimentdata',
            name='import_columns',
        ),
        migrations.DeleteModel(
            name='EC_Cycle',
        ),
        migrations.DeleteModel(
            name='ExperimentData',
        ),
        migrations.AddField(
            model_name='datarange',
            name='dataFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranges', to='battDB.ExperimentDataFile'),
        ),
    ]
