# Generated by Django 4.1.3 on 2022-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0033_experimentdatafile_devices"),
        ("battDB", "0033_update_parsers"),
    ]

    operations = []
