# Generated by Django 4.1.3 on 2022-12-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0032_alter_devicespecification_name_alter_equipment_name_and_more'),
        ('battDB', '0033_experimentdatafile_devices'),
    ]

    operations = [
    ]
