# Generated by Django 2.2.14 on 2020-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0034_experimentdatafile_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarange',
            name='file_offset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
