# Generated by Django 4.1.3 on 2022-12-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0034_merge_20221219_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='time_recorded',
            field=models.DateTimeField(blank=True, help_text='Time at which the experiment data was recoreded', null=True),
        ),
    ]
