# Generated by Django 4.1.3 on 2023-01-04 14:26

from django.db import migrations

from ..initial_device_types import populate_devices


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0037_alter_batch_manufacturer"),
    ]

    operations = [migrations.RunPython(populate_devices)]
