# Generated by Django 4.1.3 on 2023-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0041_alter_experiment_thermal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparameter',
            name='value',
            field=models.JSONField(default=float),
        ),
    ]
