# Generated by Django 3.1.2 on 2020-10-12 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0045_auto_20201012_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdatafile",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experimentdatafile",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=10,
            ),
        ),
        migrations.AddField(
            model_name="experimentdatafile",
            name="user_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="leave blank for default user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
