# Generated by Django 3.1.2 on 2020-10-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0048_auto_20201012_2059"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentalapparatus", name="testEquipment",
        ),
    ]
