# Generated by Django 3.1.2 on 2020-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0049_remove_experimentalapparatus_testequipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentalapparatus",
            name="testEquipment",
            field=models.ManyToManyField(
                through="battDB.ApparatusEquipment", to="battDB.Equipment"
            ),
        ),
    ]
