# Generated by Django 3.1.2 on 2020-10-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0050_experimentalapparatus_testequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cellbatch',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cellconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='celltype',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicebatch',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='experimentalapparatus',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='name',
            field=models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True),
        ),
    ]
