# Generated by Django 3.1.2 on 2020-10-13 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0052_auto_20201012_2229"),
    ]

    operations = [
        migrations.RemoveField(model_name="device", name="user_owner",),
        migrations.RemoveField(model_name="devicebatch", name="user_owner",),
        migrations.RemoveField(model_name="devicetype", name="user_owner",),
        migrations.RemoveField(
            model_name="experimentalapparatus", name="testEquipment",
        ),
        migrations.RemoveField(model_name="experimentalapparatus", name="user_owner",),
        migrations.RenameField(
            model_name="experiment", old_name="owner", new_name="user_owner",
        ),
        migrations.RemoveField(model_name="datarange", name="analysis",),
        migrations.RemoveField(model_name="datarange", name="events",),
        migrations.RemoveField(model_name="experiment", name="analysis",),
        migrations.RemoveField(model_name="experiment", name="apparatus",),
        migrations.RemoveField(model_name="experiment", name="parameters",),
        migrations.RemoveField(model_name="experimentdatafile", name="analysis",),
        migrations.RemoveField(model_name="experimentdatafile", name="import_columns",),
        migrations.RemoveField(model_name="experimentdatafile", name="metadata",),
        migrations.RemoveField(model_name="experimentdatafile", name="parameters",),
        migrations.AddField(
            model_name="cell",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="cellbatch",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="cellconfig",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="celltype",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="datarange",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="equipmenttype",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experiment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="experimentdatafile",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="rawdatafile",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="testprotocol",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="cellbatch",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="cellconfig",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="celltype",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="datarange",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="rawdatafile",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="testprotocol",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.DeleteModel(name="ApparatusEquipment",),
        migrations.DeleteModel(name="Device",),
        migrations.DeleteModel(name="DeviceBatch",),
        migrations.DeleteModel(name="DeviceType",),
        migrations.DeleteModel(name="ExperimentalApparatus",),
        migrations.DeleteModel(name="SignalType",),
    ]
