# Generated by Django 3.1.2 on 2020-10-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0053_auto_20201013_2250"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="experiment", name="unique_slugname",),
    ]
