# Generated by Django 3.1.2 on 2020-10-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0054_auto_20201014_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdatafile",
            name="raw_data_file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ExperimentData",
                to="battDB.rawdatafile",
            ),
        ),
    ]
