# Generated by Django 3.1.2 on 2020-10-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0062_auto_20201015_1713"),
    ]

    operations = [
        migrations.RemoveField(model_name="cell", name="created_on",),
        migrations.RemoveField(model_name="cellbatch", name="created_on",),
        migrations.RemoveField(model_name="cellconfig", name="created_on",),
        migrations.RemoveField(model_name="celltype", name="created_on",),
        migrations.RemoveField(model_name="datarange", name="created_on",),
        migrations.RemoveField(model_name="equipment", name="created_on",),
        migrations.RemoveField(model_name="equipmenttype", name="created_on",),
        migrations.RemoveField(model_name="experiment", name="created_on",),
        migrations.RemoveField(model_name="experimentdatafile", name="created_on",),
        migrations.RemoveField(model_name="rawdatafile", name="created_on",),
        migrations.RemoveField(model_name="testprotocol", name="created_on",),
    ]
