# Generated by Django 3.1.2 on 2020-10-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0064_auto_20201015_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=8)),
                ('unit_name', models.CharField(default='Arb', max_length=30)),
                ('unit_symbol', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
