# Generated by Django 3.1.2 on 2020-10-15 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_auto_20201015_2316"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0067_auto_20201015_2320"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Unique name for this object",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battDB.devicetype",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_mfg_cells": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.org",
                    ),
                ),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Unique name for this object",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battDB.devicebatch",
                    ),
                ),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
