# Generated by Django 3.1.2 on 2020-10-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0069_auto_20201015_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='battDB.device')),
            ],
            options={
                'abstract': False,
            },
            bases=('battDB.device',),
        ),
        migrations.AddField(
            model_name='experiment',
            name='cells',
            field=models.ManyToManyField(related_name='experiments', to='battDB.Cell'),
        ),
    ]
