# Generated by Django 3.1.2 on 2020-10-18 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0074_delete_deviceconfignode"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this object",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="cellconfig",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datarange",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devicebatch",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rawdatafile",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testprotocol",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.CreateModel(
            name="DeviceConfigNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this object",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                (
                    "deviceConfig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battDB.deviceconfig",
                    ),
                ),
                (
                    "deviceType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battDB.devicetype",
                    ),
                ),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="deviceconfig",
            name="devices",
            field=models.ManyToManyField(
                through="battDB.DeviceConfigNode", to="battDB.DeviceType"
            ),
        ),
        migrations.AddField(
            model_name="deviceconfig",
            name="user_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
