# Generated by Django 3.1.2 on 2020-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0076_auto_20201019_1209"),
    ]

    operations = [
        migrations.RemoveField(model_name="datarange", name="dataFile",),
        migrations.RemoveField(model_name="datarange", name="user_owner",),
        migrations.RemoveField(model_name="devicebatch", name="device_type",),
        migrations.RemoveField(model_name="devicebatch", name="manufacturer",),
        migrations.RemoveField(model_name="devicebatch", name="user_owner",),
        migrations.RemoveField(model_name="deviceconfig", name="devices",),
        migrations.RemoveField(model_name="deviceconfig", name="user_owner",),
        migrations.RemoveField(model_name="deviceconfignode", name="deviceConfig",),
        migrations.RemoveField(model_name="deviceconfignode", name="deviceType",),
        migrations.RemoveField(model_name="deviceconfignode", name="user_owner",),
        migrations.RemoveField(model_name="devicetype", name="user_owner",),
        migrations.RemoveField(model_name="equipment", name="type",),
        migrations.RemoveField(model_name="equipment", name="user_owner",),
        migrations.RemoveField(model_name="equipmenttype", name="user_owner",),
        migrations.RemoveField(model_name="experimentdatafile", name="experiment",),
        migrations.RemoveField(model_name="experimentdatafile", name="machine",),
        migrations.RemoveField(model_name="experimentdatafile", name="raw_data_file",),
        migrations.RemoveField(model_name="experimentdatafile", name="user_owner",),
        migrations.RemoveField(model_name="experiment", name="cellConfig",),
        migrations.RemoveField(model_name="experiment", name="protocol",),
        migrations.RemoveField(model_name="experiment", name="status",),
        migrations.AddField(
            model_name="experiment",
            name="slug",
            field=models.SlugField(default="bork", editable=False),
        ),
        migrations.AddField(
            model_name="rawdatafile",
            name="slug",
            field=models.SlugField(default="bork", editable=False),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name for this object", max_length=128, null=True
            ),
        ),
        migrations.DeleteModel(name="CellConfig",),
        migrations.DeleteModel(name="DataRange",),
        migrations.DeleteModel(name="DeviceBatch",),
        migrations.DeleteModel(name="DeviceConfig",),
        migrations.DeleteModel(name="DeviceConfigNode",),
        migrations.DeleteModel(name="DeviceType",),
        migrations.DeleteModel(name="Equipment",),
        migrations.DeleteModel(name="EquipmentType",),
        migrations.DeleteModel(name="ExperimentDataFile",),
    ]
