# Generated by Django 3.1.2 on 2020-10-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0078_auto_20201020_0903"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="battDB.device",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("battDB.device",),
        ),
        migrations.RemoveField(model_name="deviceconfignode", name="attributes",),
        migrations.RemoveField(model_name="deviceconfignode", name="created_on",),
        migrations.RemoveField(model_name="deviceconfignode", name="modified_on",),
        migrations.RemoveField(model_name="deviceconfignode", name="name",),
        migrations.RemoveField(model_name="deviceconfignode", name="notes",),
        migrations.RemoveField(model_name="deviceconfignode", name="slug",),
        migrations.RemoveField(model_name="deviceconfignode", name="status",),
        migrations.RemoveField(model_name="deviceconfignode", name="user_owner",),
    ]
