# Generated by Django 3.1.2 on 2020-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0080_auto_20201020_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconfig",
            name="devices",
            field=models.ManyToManyField(
                through="battDB.DeviceConfigNode", to="battDB.Device"
            ),
        ),
    ]
