# Generated by Django 3.1.2 on 2020-10-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_auto_20201021_1112"),
        ("battDB", "0083_device_serialno"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
    ]
