# Generated by Django 3.1.2 on 2020-10-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0084_device_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(help_text='Parent device specification', limit_choices_to={'is_template': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serialNo',
            field=models.CharField(blank=True, help_text='Serial Number - or format, for device templates', max_length=60, null=True),
        ),
    ]
