# Generated by Django 3.1.2 on 2020-10-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0085_auto_20201021_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceconfignode',
            old_name='Device_terminal_name',
            new_name='device_terminal_name',
        ),
        migrations.RenameField(
            model_name='deviceconfignode',
            old_name='Net_name',
            new_name='net_name',
        ),
        migrations.AlterField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent device specification', limit_choices_to={'is_template': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.device'),
        ),
    ]
