# Generated by Django 3.1.2 on 2020-10-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0091_auto_20201022_1947"),
    ]

    operations = [
        migrations.RemoveField(model_name="device", name="parent_specification",),
        migrations.AddField(
            model_name="device",
            name="parent_device",
            field=models.ForeignKey(
                blank=True,
                help_text="If this device is part of a module or pack, link to it here",
                limit_choices_to={"devType": (30, 40)},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_devices",
                to="battDB.device",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent device specification",
                limit_choices_to={"is_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specified_devices",
                to="battDB.device",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="terminals",
            field=models.TextField(
                default="positive, negative",
                help_text="comma-separated list of terminal names",
                null=True,
            ),
        ),
    ]
