# Generated by Django 3.1.2 on 2020-10-27 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0097_MPTT_Device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="devType",
            field=models.CharField(
                choices=[
                    ("cell", "Single cell"),
                    ("module", "Module containing multiple cells"),
                    ("battery", "Battery containing cells OR modules"),
                    ("sensor", "Sensor attached to a device"),
                    ("cycler", "Cycler Machine"),
                ],
                default="cell",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="deviceconfignode",
            name="device",
            field=models.ForeignKey(
                help_text="Related device specification e.g. cell or sensor. Must have is_template=True",
                limit_choices_to={"inherit_metadata": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="battDB.device",
            ),
        ),
    ]
