# Generated by Django 3.1.2 on 2020-10-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0099_experimentThing"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="batch_size",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="If this record describes a batch of identical devices, enter the batch size here",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="devType",
            field=models.CharField(
                choices=[
                    ("component", "Component part of a cell, such as an electrode"),
                    ("cell", "Single cell"),
                    ("module", "Module or small pack containing multiple cells"),
                    ("battery", "Modular battery pack containing sub-modules"),
                    ("sensor", "Sensor attached to a device"),
                    ("cycler", "Cycler Machine"),
                ],
                default="cell",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serialNo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Serial Number - or format, for device templates",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="BatchDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_index", models.PositiveSmallIntegerField(default=1)),
                (
                    "serialNo",
                    models.CharField(
                        blank=True, default="", help_text="Serial Number", max_length=60
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="battDB.device"
                    ),
                ),
            ],
            options={"unique_together": {("batch", "batch_index")},},
        ),
    ]
