# Generated by Django 3.1.2 on 2020-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0100_BatchDevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdevice',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata'),
        ),
    ]
