# Generated by Django 3.1.2 on 2020-10-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battDB', '0106_ReinstateDataFile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='thing_ptr',
        ),
        migrations.AddField(
            model_name='experiment',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='battDB.device'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.CharField(blank=True, help_text='Name for this object', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional human-readable notes', null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=10),
        ),
        migrations.AddField(
            model_name='experiment',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
