# Generated by Django 3.1.2 on 2020-10-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0033_auto_20201021_1112"),
        ("battDB", "0109_DeviceData"),
    ]

    operations = [
        migrations.AlterModelOptions(name="device", options={},),
        migrations.AlterField(
            model_name="devicedata",
            name="parameter",
            field=models.ForeignKey(
                default=4,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dfndb.parameter",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in",
                to="battDB.device",
            ),
        ),
    ]
