# Generated by Django 3.1.2 on 2020-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0114_DataColumn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceData',
        ),
    ]
