# Generated by Django 3.1.2 on 2020-10-29 11:47

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0047_auto_20201028_1112"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0116_DataColumnBork"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this object",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="autogenerated",
                        editable=False,
                        help_text="Auto-generated unique name, can be used in URLs",
                    ),
                ),
                (
                    "serialNo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Batch number, optionally indicate serial number format",
                        max_length=60,
                    ),
                ),
                ("batch_size", models.PositiveSmallIntegerField(default=1)),
                ("manufactured_on", models.DateField(default=datetime.datetime.now)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.org",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Device Batches",},
        ),
        migrations.CreateModel(
            name="DeviceSpecification",
            fields=[
                (
                    "thing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.thing",
                    ),
                ),
                (
                    "devType",
                    models.CharField(
                        choices=[
                            ("component", "Component part of a cell"),
                            ("cell", "Single cell"),
                            ("module", "Module containing cells"),
                            ("battery", "Battery pack containing modules"),
                            ("sensor", "Sensor attached to a device"),
                            ("cycler", "Cycler Machine"),
                        ],
                        default="cell",
                        max_length=16,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("common.thing",),
        ),
        migrations.RemoveField(model_name="device", name="manufacturer",),
        migrations.RemoveField(model_name="device", name="specification",),
        migrations.RemoveField(model_name="device", name="thing_ptr",),
        migrations.DeleteModel(name="DeviceList",),
        migrations.AlterModelOptions(
            name="datacolumn",
            options={
                "verbose_name": "Column Mapping",
                "verbose_name_plural": "Data Column Mappings to Device Parameters",
            },
        ),
        migrations.AddField(
            model_name="devicebatch",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                help_text="Copy metadata from another device?",
                limit_choices_to={"inherit_metadata": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.devicespecification",
            ),
        ),
        migrations.AddField(
            model_name="devicebatch",
            name="user_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="batchdevice",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battDB.devicebatch"
            ),
        ),
        migrations.AlterField(
            model_name="datacolumn",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battDB.devicebatch"
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in",
                to="battDB.devicespecification",
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="mappings",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_files",
                through="battDB.DataColumn",
                to="battDB.DeviceBatch",
            ),
        ),
        migrations.DeleteModel(name="Device",),
    ]
