# Generated by Django 3.1.2 on 2020-10-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0033_auto_20201021_1112'),
        ('battDB', '0117_DeviceSpecificationBatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebatch',
            options={'verbose_name_plural': '2. Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicespecification',
            options={'verbose_name_plural': '1. Device Specifications'},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'dataset', 'verbose_name_plural': '3. Experiments'},
        ),
        migrations.AlterModelOptions(
            name='experimentdatafile',
            options={'verbose_name': 'dataset', 'verbose_name_plural': '4. Data Files'},
        ),
        migrations.RenameField(
            model_name='devicespecification',
            old_name='devType',
            new_name='device_type',
        ),
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.devicespecification')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dfndb.material')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.parameter')),
            ],
            options={
                'unique_together': {('data', 'parameter', 'material')},
            },
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='parameters',
            field=models.ManyToManyField(through='battDB.DeviceParameter', to='dfndb.Parameter'),
        ),
    ]
