# Generated by Django 3.1.2 on 2020-10-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0047_auto_20201028_1112"),
        ("battDB", "0118_DeviceParameter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicebatch", options={"verbose_name_plural": "Devices"},
        ),
        migrations.AlterModelOptions(
            name="devicespecification",
            options={"verbose_name_plural": "Device Specifications"},
        ),
        migrations.AlterModelOptions(
            name="experiment",
            options={"verbose_name": "dataset", "verbose_name_plural": "Experiments"},
        ),
        migrations.AlterModelOptions(
            name="experimentdatafile",
            options={"verbose_name": "dataset", "verbose_name_plural": "Data Files"},
        ),
        migrations.RemoveField(model_name="devicebatch", name="attributes",),
        migrations.RemoveField(model_name="devicebatch", name="created_on",),
        migrations.RemoveField(model_name="devicebatch", name="id",),
        migrations.RemoveField(model_name="devicebatch", name="modified_on",),
        migrations.RemoveField(model_name="devicebatch", name="name",),
        migrations.RemoveField(model_name="devicebatch", name="notes",),
        migrations.RemoveField(model_name="devicebatch", name="slug",),
        migrations.RemoveField(model_name="devicebatch", name="status",),
        migrations.RemoveField(model_name="devicebatch", name="user_owner",),
        migrations.AddField(
            model_name="devicebatch",
            name="thing_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="common.thing",
            ),
            preserve_default=False,
        ),
    ]
