# Generated by Django 3.1.2 on 2020-10-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0122_AbstractSpec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicespecification',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='devicebatch',
            name='specification',
            field=models.ForeignKey(blank=True, help_text='Batch Specification', limit_choices_to={'abstract': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.devicespecification'),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='abstract',
            field=models.BooleanField(default=False, help_text="This specifies an abstract device, e.g. 'Cell' with child members such as'Positive Electrode, Negative Electrode, Electrolyte etc. <BR>If this is set to True, then all metadata declared here must be overridden in child classes. An abstract specification cannot be used to define a physical device or batch. <BR>There should be at least one abstract specification in the database for each device type listed below.", verbose_name='Abstract Specification'),
        ),
    ]
