# Generated by Django 3.1.2 on 2020-10-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0126_DeviceParamSpec"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicebatch",
            options={
                "verbose_name": "Device or Batch",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AlterField(
            model_name="deviceconfignode",
            name="device",
            field=models.ForeignKey(
                help_text="Related device specification e.g. cell or sensor. Must have is_template=True",
                limit_choices_to={"abstract": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="battDB.devicespecification",
            ),
        ),
    ]
