# Generated by Django 3.1.2 on 2020-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0128_auto_20201030_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicespecification",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="This device is complete - it can be used ion experiments",
            ),
        ),
    ]
