# Generated by Django 3.1.2 on 2020-10-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0129_devicespecification_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicespecification",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="This device is complete - it can be used in experiments without a parent",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="device",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"abstract": False, "complete": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in",
                to="battDB.devicespecification",
            ),
        ),
    ]
