# Generated by Django 3.1.2 on 2020-11-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0050_ExperimentDataFile"),
        ("battDB", "0133_RecreateAllModels"),
    ]

    operations = [
        migrations.RemoveField(model_name="experimentdatafile", name="file_hash",),
        migrations.AddField(
            model_name="experiment",
            name="data_files",
            field=models.ManyToManyField(
                through="battDB.ExperimentDataFile", to="common.UploadedFile"
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="raw_data_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.uploadedfile",
            ),
        ),
    ]
