# Generated by Django 3.1.2 on 2020-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0135_DataColumn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datarange",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="devicebatch",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="deviceconfig",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="devicespecification",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
    ]
