# Generated by Django 3.1.2 on 2020-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0137_auto_20201101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparameter',
            name='inherit_to_children',
            field=models.BooleanField(default=False),
        ),
    ]
