# Generated by Django 3.1.2 on 2020-11-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0139_auto_20201101_1739"),
    ]

    operations = [
        migrations.RemoveField(model_name="devicebatch", name="name",),
    ]
