# Generated by Django 3.1.2 on 2020-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0143_dataparser_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='parsed_metadata',
            field=models.JSONField(default=dict, editable=False, help_text='metadata automatically extracted from the file'),
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='parsed_data',
            field=models.JSONField(default=dict, editable=False, help_text='Data automatically extracted from the file'),
        ),
    ]
