# Generated by Django 3.1.2 on 2020-11-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0145_experiment_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceconfignode", name="device_terminal_name",
        ),
        migrations.RemoveField(model_name="deviceconfignode", name="net_name",),
        migrations.RemoveField(model_name="deviceconfignode", name="next",),
        migrations.AddField(
            model_name="deviceconfignode",
            name="neg_netname",
            field=models.CharField(
                blank=True,
                help_text="Name of electrical signal at negative terminal e.g. pack_-ve",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deviceconfignode",
            name="pos_netname",
            field=models.CharField(
                blank=True,
                help_text="Name of electrical signal at positive terminal e.g. cell_1_v",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deviceconfignode",
            name="device",
            field=models.ForeignKey(
                help_text="Related device specification e.g. cell or sensor.",
                limit_choices_to={"abstract": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="battDB.devicespecification",
            ),
        ),
    ]
