# Generated by Django 3.1.2 on 2020-11-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0146_DeviceConfigNetNames"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment", options={"verbose_name_plural": "Equipment"},
        ),
        migrations.AddField(
            model_name="experimentdatafile",
            name="machine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.equipment",
            ),
        ),
    ]
