# Generated by Django 3.1.2 on 2020-11-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0052_auto_20201102_1552"),
        ("battDB", "0151_auto_20201102_1621"),
    ]

    operations = [
        migrations.RemoveField(model_name="experimentdatafile", name="use_parser",),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="raw_data_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_by",
                to="common.uploadedfile",
            ),
        ),
    ]
