# Generated by Django 3.1.2 on 2020-11-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_auto_20201102_1552'),
        ('dfndb', '0037_ManufacturingProtocol'),
        ('battDB', '0153_experimentdatafile_use_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebatch',
            name='manufacturing_protocol',
            field=models.ForeignKey(blank=True, help_text='Test protocol used in this experiment', limit_choices_to={'type': 3000}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfndb.method'),
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='raw_data_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by', to='common.uploadedfile'),
        ),
    ]
