# Generated by Django 3.1.2 on 2020-11-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0155_FileFolder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Harvester",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="autogenerated",
                        editable=False,
                        help_text="Auto-generated unique name, can be used in URLs",
                        max_length=500,
                    ),
                ),
                (
                    "file_types",
                    models.CharField(
                        default="*.csv",
                        help_text="File type pattern to monitor",
                        max_length=20,
                    ),
                ),
                (
                    "parser",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("auto", "Auto-detect"),
                            ("csv", "Generic CSV/TSV"),
                            ("biologic", "Biologic CSV/TSV/MPT"),
                            ("maccor", "Maccor XLS/XLSX"),
                            ("ivium", "Ivium TXT"),
                            ("novonix", "Novonix TXT"),
                        ],
                        default="csv",
                        help_text="Default parser to use",
                        max_length=20,
                    ),
                ),
                (
                    "attach_to_equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battDB.equipment",
                    ),
                ),
                (
                    "attach_to_experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battDB.experiment",
                    ),
                ),
                (
                    "upload_to_folder",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battDB.filefolder",
                    ),
                ),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_token",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authtoken.token",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
