# Generated by Django 3.1.2 on 2020-11-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0037_ManufacturingProtocol'),
        ('battDB', '0156_Harvester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('file_format', models.CharField(choices=[('none', 'None'), ('auto', 'Auto-detect'), ('csv', 'Generic CSV/TSV'), ('biologic', 'Biologic CSV/TSV/MPT'), ('maccor', 'Maccor XLS/XLSX'), ('ivium', 'Ivium TXT'), ('novonix', 'Novonix TXT')], default='auto', help_text="File format override, or use 'auto' to attempt detection", max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(default='', max_length=50)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.parameter')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.parser')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='dataParser',
        ),
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='use_parser',
        ),
        migrations.RemoveField(
            model_name='harvester',
            name='parser',
        ),
        migrations.DeleteModel(
            name='DataParser',
        ),
        migrations.AddField(
            model_name='parser',
            name='parameters',
            field=models.ManyToManyField(through='battDB.SignalType', to='dfndb.Parameter'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='default_parser',
            field=models.ForeignKey(blank=True, help_text="Default parser for this equipment's data", null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.parser'),
        ),
    ]
