# Generated by Django 3.1.2 on 2020-11-10 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0158_experimentdatafile_use_parser"),
    ]

    operations = [
        migrations.AddField(
            model_name="parser",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AddField(
            model_name="parser",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parser",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parser",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="parser",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=10,
            ),
        ),
        migrations.AddField(
            model_name="parser",
            name="user_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
