# Generated by Django 3.1.2 on 2020-11-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0164_deviceconfig_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='config',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_type': 'expmt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='battDB.deviceconfig'),
        ),
    ]
