# Generated by Django 3.1.2 on 2020-11-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0165_auto_20201112_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='folder',
        ),
        migrations.AddField(
            model_name='experiment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.filefolder'),
        ),
    ]
