# Generated by Django 3.1.2 on 2020-11-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0168_DataColumn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datacolumn", old_name="data", new_name="data_file",
        ),
        migrations.RemoveField(model_name="experimentdatafile", name="mappings",),
        migrations.CreateModel(
            name="ExperimentDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.PositiveSmallIntegerField(default=0)),
                (
                    "device_pos",
                    models.CharField(
                        default="cell_nn",
                        help_text="Device Position ID in Experiment Config - e.g. Cell_A1 for the first cell ofa series-parallel pack",
                        max_length=20,
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battDB.experimentdatafile",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="battDB.devicebatch",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battDB.experiment",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("experiment", "device", "batch_id", "data_file"),
                    ("device_pos", "data_file"),
                },
            },
        ),
        migrations.AddField(
            model_name="experimentdatafile",
            name="devices",
            field=models.ManyToManyField(
                related_name="used_in",
                through="battDB.ExperimentDevice",
                to="battDB.DeviceBatch",
            ),
        ),
        migrations.AlterField(
            model_name="datacolumn",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Device id for parameter mapping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.experimentdevice",
            ),
        ),
        migrations.RemoveField(model_name="datacolumn", name="batch_id",),
    ]
