# Generated by Django 3.1.2 on 2020-11-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0169_ExperimentDevice"),
    ]

    operations = [
        migrations.DeleteModel(name="DataColumn",),
    ]
