# Generated by Django 3.1.2 on 2020-11-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0171_datacolumn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdevice",
            name="data_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.experimentdatafile",
            ),
        ),
        migrations.AlterField(
            model_name="experimentdevice",
            name="device",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="battDB.devicebatch",
            ),
            preserve_default=False,
        ),
    ]
