# Generated by Django 3.1.2 on 2020-11-12 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0173_auto_20201112_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdevice',
            name='batch_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='sequence number of device within batch', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
