# Generated by Django 3.1.2 on 2020-11-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0174_auto_20201112_1519"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experimentdevice", old_name="batch_id", new_name="batch_seq",
        ),
        migrations.AlterUniqueTogether(
            name="experimentdevice",
            unique_together={
                ("experiment", "deviceBatch", "batch_seq", "data_file"),
                ("device_pos", "data_file"),
            },
        ),
    ]
