# Generated by Django 3.1.2 on 2020-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0178_auto_20201112_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebatch',
            name='serialNo',
            field=models.CharField(blank=True, default='%d', help_text='Batch number, optionally indicate serial number format', max_length=60),
        ),
    ]
