# Generated by Django 3.1.2 on 2020-11-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0179_auto_20201112_1710"),
    ]

    operations = [
        migrations.RemoveField(model_name="harvester", name="upload_to_folder",),
    ]
