# Generated by Django 3.1.2 on 2020-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0181_auto_20201112_1803"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaltype",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
