# Generated by Django 3.1.2 on 2020-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0182_signaltype_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaltype",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="override column ordering"
            ),
        ),
    ]
