# Generated by Django 3.1.2 on 2020-11-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0185_auto_20201112_2108"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datarange", old_name="file_offset", new_name="file_offset_end",
        ),
        migrations.AddField(
            model_name="datarange",
            name="file_offset_start",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datarange",
            name="label",
            field=models.CharField(default="all", max_length=32),
        ),
        migrations.AlterField(
            model_name="experimentdevice",
            name="device_pos",
            field=models.CharField(
                default="cell_xx",
                help_text="Device Position ID in Experiment Config - e.g. Cell_A1 for the first cell ofa series-parallel pack",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="experimentdevice",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="battDB.experiment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datarange", unique_together={("dataFile", "label")},
        ),
    ]
