# Generated by Django 3.1.2 on 2020-11-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0186_auto_20201113_1317"),
    ]

    operations = [
        migrations.RemoveField(model_name="datarange", name="name",),
        migrations.AlterField(
            model_name="datarange",
            name="protocol_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="signaltype",
            name="parser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="battDB.parser",
            ),
        ),
    ]
