# Generated by Django 3.1.2 on 2020-11-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0188_dataRange"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvester",
            name="parser_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.parser",
            ),
        ),
    ]
