# Generated by Django 3.1.2 on 2020-11-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0190_harvester_local_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='parse',
            field=models.BooleanField(default=False),
        ),
    ]
