# Generated by Django 3.1.2 on 2020-11-30 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0052_auto_20201102_1552"),
        ("battDB", "0191_experimentdatafile_parse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdatafile",
            name="parse",
            field=models.BooleanField(
                default=False, help_text="Set to True to import data on save"
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatafile",
            name="raw_data_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.uploadedfile",
            ),
        ),
    ]
