# Generated by Django 3.1.2 on 2020-12-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0192_edf_1to1_uf"),
    ]

    operations = [
        migrations.RemoveField(model_name="devicebatch", name="status",),
        migrations.RemoveField(model_name="deviceconfig", name="status",),
        migrations.RemoveField(model_name="devicespecification", name="status",),
        migrations.RemoveField(model_name="equipment", name="status",),
        migrations.RemoveField(model_name="experiment", name="status",),
        migrations.RemoveField(model_name="experimentdatafile", name="status",),
        migrations.RemoveField(model_name="filefolder", name="status",),
        migrations.RemoveField(model_name="harvester", name="status",),
        migrations.RemoveField(model_name="parser", name="status",),
    ]
