# Generated by Django 3.1.2 on 2020-12-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0194_status_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="experimentdatafile", name="use_parser",),
    ]
