# Generated by Django 3.1.2 on 2020-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0195_use_parser_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdatafile",
            name="use_parser",
            field=models.SlugField(default="autodetect", max_length=20),
        ),
    ]
