# Generated by Django 3.1.2 on 2020-12-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("battDB", "0198_auto_20201208_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("published", "Published"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="uploaded_files")),
                (
                    "hash",
                    models.CharField(
                        editable=False,
                        help_text="SHA-1 Hash of uploaded file. You cannot upload the same file twice.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="experiment", name="folder",),
        migrations.AlterUniqueTogether(
            name="experimentdatafile", unique_together=set(),
        ),
        migrations.DeleteModel(name="FileFolder",),
        migrations.RemoveField(model_name="experimentdatafile", name="raw_data_file",),
        migrations.RemoveField(model_name="experimentdatafile", name="use_parser",),
    ]
