# Generated by Django 3.1.2 on 2020-12-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0200_FilesRefactor2"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedfile", name="created_on",),
        migrations.RemoveField(model_name="uploadedfile", name="modified_on",),
        migrations.RemoveField(model_name="uploadedfile", name="status",),
        migrations.RemoveField(model_name="uploadedfile", name="user_owner",),
        migrations.AddField(
            model_name="uploadedfile",
            name="edf",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battDB.experimentdatafile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="experimentdatafile", unique_together=set(),
        ),
        migrations.RemoveField(model_name="experimentdatafile", name="raw_data_file",),
    ]
