# Generated by Django 3.1.2 on 2020-12-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0041_status_text"),
        ("battDB", "0204_FilesRefactor6"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdatafile",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                help_text="Test protocol used in this experiment",
                limit_choices_to={"type": 2000},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dfndb.method",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="protocol",
            field=models.TextField(
                blank=True, help_text="Test protocol used in this experiment", null=True
            ),
        ),
    ]
