# Generated by Django 3.1.4 on 2021-01-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0207_auto_20210118_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacolumn',
            options={'verbose_name': 'Column Mapping', 'verbose_name_plural': 'Data Column Mappings to Device Parameters'},
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='data_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='battDB.experimentdatafile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device id for parameter mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.experimentdevice'),
        ),
        migrations.AlterUniqueTogether(
            name='datacolumn',
            unique_together={('column_name', 'data_file'), ('device', 'data_file')},
        ),
        migrations.RemoveField(
            model_name='datacolumn',
            name='file',
        ),
    ]
