repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.29.2"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Prettier supports many other file formats (e.g., JavaScript, HTML; see
        # https://prettier.io for list). Add other types here.
        types_or: [yaml, json]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.7"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        exclude: battDB/migrations/|common/migrations/|dfndb/migrations/|_other/|data/
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "MD013", "--disable", "MD033"]
