[tool.black]
exclude = "venv/|battDB/migrations/|common/migrations/|dfndb/migrations/|other/|data/"

[tool.isort]
known_third_party = ["django", "idutils", "mptt", "pandas", "rest_framework", "xlrd", "yaml"]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
