# Generated by Django 2.2.14 on 2020-08-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0003_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.Manufacturer'),
        ),
    ]
