# Generated by Django 2.2.14 on 2020-08-16 13:24

import battDB.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0029_remove_experimentdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=battDB.models.resultData_schema),
        ),
    ]
