# Generated by Django 3.1.2 on 2020-10-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DOI", common.models.DOIField(max_length=128, unique=True)),
                ("paper_tag", models.SlugField(max_length=100, unique=True)),
                ("year", common.models.YearField(default=2020)),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=40)),
                ("lastName", models.CharField(max_length=40)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "authUser",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.org",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="org",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="head_of",
                to="common.person",
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_orgs",
                to="common.org",
            ),
        ),
    ]
