# Generated by Django 3.2.8 on 2021-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='draft', max_length=16),
        ),
    ]
