# Generated by Django 3.2.8 on 2021-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_paper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16),
        ),
    ]
