# Generated by Django 3.2.8 on 2021-11-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_paper_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='year',
        ),
    ]
