# Generated by Django 3.2.8 on 2021-11-15 13:57

from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20211115_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('deleted', 'Deleted')], default='private', max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata')),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('slug', models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs', max_length=500)),
                ('DOI', common.models.DOIField(blank=True, help_text='DOI for the reference.', max_length=128, null=True, unique=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('url', models.URLField(blank=True, null=True)),
                ('PDF', models.FileField(blank=True, help_text='Optional PDF copy', null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user_owner',
        ),
    ]
