# Generated by Django 3.2.8 on 2021-11-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dfndb', '0004_auto_20211115_1357'),
        ('common', '0005_auto_20211115_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.AddField(
            model_name='reference',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
