# Generated by Django 3.1.2 on 2020-10-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_auto_20201011_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='head',
        ),
        migrations.RemoveField(
            model_name='org',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='org',
            name='type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='authUser',
        ),
        migrations.RemoveField(
            model_name='person',
            name='org',
        ),
        migrations.AddField(
            model_name='org',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AddField(
            model_name='org',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='is_mfg_cells',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='is_mfg_equip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='is_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='org',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='nobody', help_text='Unique name for this object', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='person',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
    ]
