# Generated by Django 3.1.2 on 2020-10-13 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0010_auto_20201012_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional human-readable notes', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional human-readable notes', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional human-readable notes', null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata'),
        ),
        migrations.AlterField(
            model_name='person',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata'),
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=10)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata')),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=10)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata')),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Unique name for this object', max_length=128, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=10)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata')),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.devicetype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.org')),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
