# Generated by Django 3.1.2 on 2020-10-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_auto_20201013_2250"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="PDF",
            field=models.FileField(
                blank=True, help_text="Optional PDF copy", null=True, upload_to=""
            ),
        ),
    ]
