# Generated by Django 3.1.2 on 2020-10-15 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0012_paper_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='user_owner',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='org',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='org',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='org',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='org',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='org_owners',
        ),
        migrations.RemoveField(
            model_name='person',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_owner',
        ),
        migrations.AddField(
            model_name='person',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.org'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(default='unnamed', help_text='Organisation name', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(help_text='Contributing Persons.', related_name='papers', to='common.Person'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publisher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_publisher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.org'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='unnamed', help_text="Person's shortened name (must be unique) e.g. 'D.W. Jones'", max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
