# Generated by Django 3.1.2 on 2020-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_auto_20201015_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
