# Generated by Django 3.1.2 on 2020-10-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_auto_20201015_1718"),
    ]

    operations = [
        migrations.RemoveField(model_name="paper", name="name",),
        migrations.AddField(
            model_name="device",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.batch",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Cell"), (10, "Cycler"), (30, "Module"), (40, "Sensor")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_mfg_cells": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
    ]
