# Generated by Django 3.1.2 on 2020-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_auto_20201015_2316"),
    ]

    operations = [
        migrations.RemoveField(model_name="paper", name="authors",),
    ]
