# Generated by Django 3.1.2 on 2020-10-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_remove_paper_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_principal", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.person"
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.paper"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paper",
            name="authors",
            field=models.ManyToManyField(
                help_text="Contributing Persons.",
                related_name="papers",
                through="common.PaperAuthor",
                to="common.Person",
            ),
        ),
    ]
