# Generated by Django 3.1.2 on 2020-10-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_auto_20201016_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="org",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation that this person belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
    ]
