# Generated by Django 3.1.2 on 2020-10-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0025_auto_20201016_1404"),
    ]

    operations = [
        migrations.RemoveField(model_name="paper", name="tag",),
        migrations.AddField(
            model_name="paper",
            name="slug",
            field=models.SlugField(default="foo", editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BaseModelWithSlug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this object",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Submitted"),
                            (30, "Accepted"),
                            (40, "Published"),
                            (50, "Deleted"),
                        ],
                        default=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional machine-readable JSON metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional human-readable notes", null=True
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "user_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
