# Generated by Django 3.1.2 on 2020-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0028_remove_paper_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="slug",
            field=models.SlugField(default="bork", editable=False),
        ),
    ]
