# Generated by Django 3.1.2 on 2020-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_paper_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
    ]
