# Generated by Django 3.1.2 on 2020-10-21 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_auto_20201021_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="org",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="org",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="slug",
            field=models.SlugField(
                default="autogenerated",
                editable=False,
                help_text="Auto-generated unique name, can be used in URLs",
            ),
        ),
    ]
