# Generated by Django 3.1.2 on 2020-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_auto_20201026_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="authors",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(default="", max_length=300),
        ),
    ]
