# Generated by Django 3.1.2 on 2020-10-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_compositeThing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='composition',
        ),
        migrations.AddField(
            model_name='thing',
            name='is_composite',
            field=models.BooleanField(default=False, help_text='Is this thing composed of other things?'),
        ),
        migrations.AddField(
            model_name='thing',
            name='part_of',
            field=models.ForeignKey(help_text='Is this Thing a physical part of another Thing?', limit_choices_to={'is_composite': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='common.thing'),
        ),
        migrations.DeleteModel(
            name='ThingComposition',
        ),
    ]
