# Generated by Django 3.1.2 on 2020-10-26 14:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0035_ThingParts"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thing",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thing",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thing",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thing",
            name="part_of",
            field=mptt.fields.TreeForeignKey(
                help_text="Is this Thing a physical part of another Thing?",
                limit_choices_to={"is_composite": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="common.thing",
            ),
        ),
    ]
