# Generated by Django 3.1.2 on 2020-10-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_MPTT_Thing_parent_revert"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thing", old_name="parent", new_name="parent_assembly",
        ),
    ]
