# Generated by Django 3.1.2 on 2020-10-26 16:31

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_MPTT_Thing_parent_rev2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="parent_assembly",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Is this Thing a physical part of another Thing?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="common.thing",
            ),
        ),
        migrations.AlterField(
            model_name="thing",
            name="specification",
            field=models.ForeignKey(
                blank=True,
                help_text="Is this Thing specified by another Thing (it inherits its attributes)",
                limit_choices_to={"is_specification": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specifies",
                to="common.thing",
            ),
        ),
    ]
