# Generated by Django 3.1.2 on 2020-10-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20201026_1631"),
    ]

    operations = [
        migrations.DeleteModel(name="Thing",),
    ]
