# Generated by Django 3.1.2 on 2020-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20201027_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='inherit_metadata',
            field=models.BooleanField(default=True, help_text='Set to True if this object does not describe a real life thing, but a specification, type or grouping. In this case, the metadata will be inherited.', verbose_name='Inherit metadata from parent'),
        ),
    ]
