# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battDB", "0131_Bork"),
        ("common", "0048_Docstrings"),
    ]

    operations = [
        migrations.DeleteModel(name="Thing",),
    ]
