# Generated by Django 3.1.2 on 2020-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0049_Bork"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="uploaded_files")),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={"abstract": False,},
        ),
    ]
