# Generated by Django 3.1.2 on 2020-12-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_auto_20201102_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='status',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='status',
        ),
    ]
