BT-LAB SETTING FILE

Number of linked techniques : 1

Filename : D:\Niall\NDK01\NDK01-80\NDK01-80 - 2nd attempt - CC charging profiles at 0,1 to 0,7C - 25degC - cell C.mps

Device : BCS-815
Ecell ctrl range : min = 0.00 V, max = 9.00 V
Safety Limits :
	Ecell min = 2.45 V
	Ecell max = 4.25 V
	for t > 100 ms
	Temperature max = 55.00 °C
Electrode material : 
Initial state : 
Electrolyte : 
Comments : 
Mass of active material : 0.001 mg
 at x = 0.000
Molecular weight of active material (at x = 0) : 0.001 g/mol
Atomic weight of intercalated ion : 0.001 g/mol
Acquisition started at : xo = 0.000
Number of e- transfered per intercalated ion : 1
for DX = 1, DQ = 26.802 mA.h
Battery capacity : 1.000 A.h
Electrode surface area : 0.001 cm²
Characteristic mass : 0.001 g
Record Temperature
Cycle Definition : Charge/Discharge alternance
Do not turn to OCV between techniques

Technique : 1
Modulo Bat
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  
ctrl_type           Rest                CC                  CV                  Rest                CC                  Rest                Rest                CC                  Rest                CC                  Rest                Rest                CC                  Rest                CC                  Rest                Rest                CC                  Rest                CC                  Rest                Rest                CC                  Rest                CC                  Rest                
Apply I/C           I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   
ctrl1_val           0.000               1.500               4.200               0.000               1.000               0.000               0.000               500.000             0.000               1.000               0.000               0.000               1.500               0.000               1.000               0.000               0.000               2.500               0.000               1.000               0.000               0.000               3.500               0.000               1.500               0.000               
ctrl1_val_unit                          A                   V                                       A                                                           mA                                      A                                                           A                                       A                                                           A                                       A                                                           A                                       A                                       
ctrl1_val_vs                            <None>              Ref                                     <None>                                                      <None>                                  <None>                                                      <None>                                  <None>                                                      <None>                                  <None>                                                      <None>                                  <None>                                  
ctrl2_val           0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
ctrl2_val_unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
ctrl2_val_vs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ctrl3_val           0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
ctrl3_val_unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
ctrl3_val_vs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
N                   1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                
charge/discharge    Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              
ctrl_seq            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
ctrl_repeat         0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
ctrl_trigger        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        
ctrl_TO_t           0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
ctrl_TO_t_unit      d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   
ctrl_Nd             6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   
ctrl_Na             1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
ctrl_corr           1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
lim_nb              1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
lim1_type           Time                Ecell               |I|                 Time                Ecell               Time                Time                Ecell               Time                Ecell               Time                Time                Ecell               Time                Ecell               Time                Time                Ecell               Time                Ecell               Time                Time                Ecell               Time                Ecell               Time                
lim1_comp           >                   >                   <                   >                   <                   >                   >                   >                   >                   <                   >                   >                   >                   >                   <                   >                   >                   >                   >                   <                   >                   >                   >                   >                   <                   >                   
lim1_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim1_value          120.000             4.200               50.000              2.000               2.500               6.000               30.000              4.200               2.000               2.500               6.000               30.000              4.200               2.000               2.500               6.000               30.000              4.200               2.000               2.500               6.000               30.000              4.200               2.000               3.600               1.000               
lim1_value_unit     s                   V                   mA                  h                   V                   h                   s                   V                   h                   V                   h                   s                   V                   h                   V                   h                   s                   V                   h                   V                   h                   s                   V                   h                   V                   h                   
lim1_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       
lim1_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  
rec_nb              1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
rec1_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
rec1_value          10.000              1.000               1.000               10.000              1.000               10.000              1.000               1.000               1.000               1.000               10.000              1.000               1.000               1.000               1.000               10.000              1.000               1.000               1.000               1.000               10.000              1.000               1.000               1.000               1.000               10.000              
rec1_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
E range min (V)     0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
E range max (V)     9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               
I Range             10 mA               10 A                10 A                10 mA               1 A                 10 mA               10 mA               1 A                 10 mA               1 A                 10 mA               10 mA               10 A                10 mA               1 A                 10 mA               10 mA               10 A                10 mA               1 A                 10 mA               10 mA               10 A                10 mA               10 A                10 mA               
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
auto rest           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
Bandwidth           4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   
