# Generated by Django 2.2.14 on 2020-09-30 17:27

import dfndb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', dfndb.models.DOIField(max_length=128, unique=True)),
                ('paper_tag', models.SlugField(max_length=100, unique=True)),
                ('year', dfndb.models.YearField(default=2020)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
