# Generated by Django 2.2.14 on 2020-10-01 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('composition', models.ManyToManyField(to='dfndb.CompositionPart')),
            ],
        ),
        migrations.AddField(
            model_name='compositionpart',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.Compound'),
        ),
    ]
