# Generated by Django 2.2.14 on 2020-10-01 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0002_auto_20201001_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='polymer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
