# Generated by Django 2.2.14 on 2020-10-01 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0003_material_polymer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'MethodType1'), (2, 'MethodType2')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('symbol', models.CharField(max_length=40, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'ParamType1'), (2, 'ParamType2')])),
                ('notes', models.TextField(blank=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfndb.QuantityUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'DataType1'), (2, 'DataType2')])),
                ('data', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.Material')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.Paper')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.Parameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
