# Generated by Django 2.2.14 on 2020-10-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0005_auto_20201001_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(1, 'Anode'), (2, 'Cathode'), (3, 'Electrolyte'), (4, 'Separator')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='type',
            field=models.IntegerField(choices=[(1, 'Experimental'), (2, 'Modelling')]),
        ),
    ]
