# Generated by Django 3.1.2 on 2020-10-16 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0012_auto_20201015_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantityunit',
            name='symbolName',
        ),
        migrations.AddField(
            model_name='quantityunit',
            name='unitName',
            field=models.CharField(blank=True, help_text="e.g. 'Coulombs'", max_length=40),
        ),
        migrations.AddField(
            model_name='quantityunit',
            name='unitSymbol',
            field=models.CharField(default='X', help_text="e.g. 'C'", max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='composition',
            field=models.ManyToManyField(help_text='e.g. NMC 622 would have 3 CompositionParts, Li 6, Manganese 2, Cobalt 2', to='dfndb.CompositionPart'),
        ),
        migrations.AlterField(
            model_name='material',
            name='polymer',
            field=models.IntegerField(default=0, help_text='If this material is a polymer, enter degree of polymerization', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quantityunit',
            name='name',
            field=models.CharField(help_text="Readable name e.g. 'Charge'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quantityunit',
            name='symbol',
            field=models.CharField(help_text="e.g. 'Q', Will be decoded as LaTeX", max_length=40, unique=True),
        ),
    ]
