# Generated by Django 3.1.2 on 2020-10-16 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0016_auto_20201016_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.compound')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.material')),
            ],
            options={
                'unique_together': {('compound', 'amount', 'material')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='composition',
            field=models.ManyToManyField(help_text='e.g. NMC 622 would have 3 Compounds, Nickel 6, Manganese 2, Cobalt 2', through='dfndb.CompositionPart', to='dfndb.Compound'),
        ),
    ]
