# Generated by Django 3.1.2 on 2020-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0036_SlugFieldMaxLen500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='type',
            field=models.IntegerField(choices=[(2000, 'Experimental'), (1000, 'Modelling'), (3000, 'Manufacture')], default=1000),
        ),
    ]
