# Generated by Django 3.1.2 on 2020-10-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20201018_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='bork', editable=False),
        ),
        migrations.DeleteModel(
            name='BaseModelWithSlug',
        ),
    ]
