# Generated by Django 3.1.2 on 2020-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20201019_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='slug',
        ),
    ]
