# Generated by Django 3.1.2 on 2020-10-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20201021_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.DeleteModel(
            name='PaperAuthor',
        ),
    ]
