# Generated by Django 3.1.2 on 2020-10-26 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0033_auto_20201026_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name for this object', max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Optional machine-readable JSON metadata')),
                ('notes', models.TextField(blank=True, help_text='Optional human-readable notes', null=True)),
                ('slug', models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs')),
                ('is_specification', models.BooleanField(default=False, help_text='Can this thing be used as a specification for other things?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThingComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='common.thing')),
                ('super_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='common.thing')),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='composition',
            field=models.ManyToManyField(related_name='parts', through='common.ThingComposition', to='common.Thing'),
        ),
        migrations.AddField(
            model_name='thing',
            name='specification',
            field=models.ForeignKey(blank=True, help_text='Is this Thing specified by another Thing (it inherits its attributes)', limit_choices_to={'is_specification': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specifies', to='common.thing'),
        ),
        migrations.AddField(
            model_name='thing',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
