# Generated by Django 3.1.2 on 2020-10-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_MPTT_Thing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='part_of',
            new_name='parent',
        ),
    ]
