# Generated by Django 3.1.2 on 2020-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_ExperimentDataFile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs', max_length=500),
        ),
    ]
