# Generated by Django 3.1.4 on 2021-01-18 13:02

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_FilesRefactor1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=common.models.YearField(default=2021),
        ),
    ]
