
database:    # Database connection config 
    auth_token: 52f1021a6e32e4202acab1c5c19f0067cc1ce38a
    host: 127.0.0.1
    port: 8000
    
harvester:
    machine_id: "partridge"      # uniquely identifies this harvester client - default is machine's hostname
    min_file_size: 1024   # do not import very small files - 1024 = 1kB
    min_file_age: 60      # do not import files modified very recently (<60s ago) - they are probably still in use
    
folders:   # Configure folders to monitor
 - "/tmp/harvester-data": 
    {
       recurse: True,                                           # set to True to descend into sub-folders, False otherwise
       auth_token: "52f1021a6e32e4202acab1c5c19f0067cc1ce38a",   # use a different auth token to assign files to a different user. FIXME: this won't work, because the initial list of hashes are currently for one user only, not all users
       experiment_id: 1,                                        # experiment ID to set in the database. Use 'None' to assign later
       file_extensions:                                        # list of file extensions to upload
       [ ".csv", ".tsv", ".mpt" ], 
       parser: "biologic",                                    # choices will be "biologic", "maccor", "ivium", "neware", etc. but currently only biologic is supported 
       columns:                                               # Columns to extract from file:  Not yet implemented - select parser config via website
       [
         "ECell/V": "Cell Voltage",
         "I/mA":    "Current"
       ]
    }
     
