COLUMN_NAME_MAPPING = {
    "time": "time/s",
    "Time": "time/s",
    "time/s": "time/s",
    "mode": "mode",
    "ox/red": "ox/red",
    "error": "error",
    "control changes": "control changes",
    "Ns changes": "Ns changes",
    "counter inc.": "counter inc",
    "Ns": "Ns",
    "I Range": "I Range",
    "control/V/mA": "control/V/mA",
    "Ecell/V": "Ecell/V",
    "Ewe/V": "Ecell/V",
    "I/mA": "I/mA",
    "dq/mA.h": "dq/mA_h",
    "(Q-Qo)/mA_h": "(Q-Qo)/mA.h",
    "Energy/W_h": "Energy/W.h",
    "Analog IN 1/V": "Analog IN 1/V",
    "Analog OUT/V": "Analog OUT/V",
    "Energy charge/W_h": "Energy charge/W.h",
    "Energy discharge/W_h": "Energy discharge/W.h",
    "Capacitance charge/µF": "Capacitance charge/µF",
    "Capacitance discharge/µF": "Capacitance discharge/µF",
    "x": "x",
    "Q discharge/mA_h": "Q discharge/mA.h",
    "Q charge/mA_h": "Q charge/mA.h",
    "Capacity/mA_h": "Capacity/mA.h",
    "Efficiency/%": "Efficiency/%",
    "control/V": "control/V",
    "control/mA": "control/mA",
    "cycle number": "cycle number",
    "P/W": "P/W",
    "R/Ohm": "R/Ohm",
    "Rec#": "Rec#",
    "RecNo": "Rec#",
}
