# Generated by Django 2.2.14 on 2020-08-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0002_auto_20200804_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.EquipmentType'),
        ),
    ]
