# Generated by Django 2.2.14 on 2020-08-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0007_auto_20200804_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentalapparatus',
            name='cellConfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.CellConfig'),
        ),
    ]
