# Generated by Django 2.2.14 on 2020-08-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0017_experiment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentalapparatus',
            options={'verbose_name_plural': 'Experimental apparatus'},
        ),
    ]
