# Generated by Django 2.2.14 on 2020-08-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0018_auto_20200812_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='apparatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.ExperimentalApparatus'),
        ),
    ]
