# Generated by Django 2.2.14 on 2020-08-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0033_auto_20200818_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_data', to='battDB.Equipment'),
        ),
    ]
