# Generated by Django 2.2.14 on 2020-09-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0035_datarange_file_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdatafile',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='battDB.Experiment'),
        ),
    ]
