# Generated by Django 2.2.14 on 2020-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0037_signaltype_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='unit',
            field=models.CharField(default='Arb', max_length=30),
        ),
    ]
