# Generated by Django 3.1.2 on 2020-10-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battDB', '0043_auto_20201010_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='cell',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cellbatch',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellbatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='cellbatch',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cellconfig',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellconfig',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='cellconfig',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celltype',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celltype',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='celltype',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentalapparatus',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentalapparatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='experimentalapparatus',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Submitted'), (30, 'Accepted'), (40, 'Published'), (50, 'Deleted')], default=20),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cell',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='cellbatch',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='cellbatch',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='cellconfig',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='cellconfig',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='experimentalapparatus',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='experimentalapparatus',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='testprotocol',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata'),
        ),
        migrations.AlterField(
            model_name='testprotocol',
            name='name',
            field=models.CharField(help_text='Unique name for this object', max_length=128, unique=True),
        ),
    ]
