# Generated by Django 3.1.2 on 2020-10-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0047_auto_20201012_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='data',
        ),
        migrations.CreateModel(
            name='ApparatusEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('Apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.experimentalapparatus')),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.equipment')),
            ],
        ),
    ]
