# Generated by Django 3.1.2 on 2020-10-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0088_auto_20201022_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='battDB.device')),
            ],
            options={
                'abstract': False,
            },
            bases=('battDB.device',),
        ),
        migrations.CreateModel(
            name='ModuleDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_position_id', models.CharField(blank=True, help_text='Position of device in pack e.g. 1 - identifies this device', max_length=20, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='battDB.device')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_members', to='battDB.compositedevice')),
            ],
        ),
        migrations.AddField(
            model_name='compositedevice',
            name='deviceList',
            field=models.ManyToManyField(related_name='my_module', through='battDB.ModuleDevice', to='battDB.Device'),
        ),
        migrations.AddField(
            model_name='compositedevice',
            name='moduleConfig',
            field=models.ForeignKey(blank=True, help_text='Module config link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_modules', to='battDB.deviceconfig'),
        ),
    ]
