# Generated by Django 3.1.2 on 2020-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0094_auto_20201026_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (20, 'Cell'), (30, 'Module'), (40, 'Pack'), (1, 'Cycler'), (10, 'Sensor')], default=0),
        ),
    ]
