# Generated by Django 3.1.2 on 2020-10-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20201027_0021'),
        ('battDB', '0098_auto_20201027_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='user_owner',
        ),
        migrations.AddField(
            model_name='experiment',
            name='thing_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.thing'),
            preserve_default=False,
        ),
    ]
