# Generated by Django 3.1.2 on 2020-10-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0102_device_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='device',
            new_name='devices',
        ),
        migrations.AlterField(
            model_name='device',
            name='specification',
            field=models.ForeignKey(blank=True, help_text='Copy metadata from another device?', limit_choices_to={'inherit_metadata': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.device'),
        ),
    ]
