# Generated by Django 3.1.2 on 2020-10-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0033_auto_20201021_1112'),
        ('battDB', '0113_auto_20201028_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='devicedata',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(max_length=20)),
                ('batch_id', models.PositiveSmallIntegerField(default=0)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.experimentdatafile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battDB.device')),
                ('parameter', models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfndb.parameter')),
            ],
            options={
                'verbose_name': 'Data File to Device Mapping',
                'verbose_name_plural': 'Data File to Device Mappings',
                'unique_together': {('device', 'data', 'batch_id')},
            },
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='signal_name',
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='data_files', through='battDB.DataColumn', to='battDB.Device'),
        ),
    ]
