# Generated by Django 3.1.2 on 2020-10-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0115_DataColumnBork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentdatafile',
            old_name='devices',
            new_name='mappings',
        ),
    ]
