# Generated by Django 3.1.2 on 2020-10-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0123_DeviceSpecType'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicespecification',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Device type. e.g. Cell, Module, Battery Pack', limit_choices_to={'abstract': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='battDB.devicespecification'),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='abstract',
            field=models.BooleanField(default=False, help_text="This specifies an abstract device, e.g. 'Cell' with child members such as'Positive Electrode, Negative Electrode, Electrolyte etc. <BR>If this is set to True, then all metadata declared here must be overridden in child classes. An abstract specification cannot be used to define a physical device or batch.", verbose_name='Abstract Specification'),
        ),
    ]
