# Generated by Django 3.1.2 on 2020-10-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0124_DeviceSpecType'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparameter',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Device type. e.g. Cell, Module, Battery Pack. <BR>An abstract specification cannot have a device type - they define the device types.', limit_choices_to={'abstract': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='battDB.devicespecification'),
        ),
    ]
