# Generated by Django 3.1.2 on 2020-10-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0034_Docstrings'),
        ('battDB', '0125_DeviceParamName'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceparameter',
            old_name='data',
            new_name='spec',
        ),
        migrations.AlterUniqueTogether(
            name='deviceparameter',
            unique_together={('spec', 'parameter', 'material'), ('spec', 'name')},
        ),
    ]
