# Generated by Django 3.1.2 on 2020-10-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0127_auto_20201030_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='device',
            field=models.ForeignKey(blank=True, limit_choices_to={'abstract': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='battDB.devicespecification'),
        ),
    ]
