# Generated by Django 3.1.2 on 2020-11-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0138_deviceparameter_inherit_to_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebatch',
            name='specification',
            field=models.ForeignKey(help_text='Batch Specification', limit_choices_to={'abstract': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.devicespecification'),
        ),
    ]
