# Generated by Django 3.1.2 on 2020-11-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0157_ParserSignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='use_parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.parser'),
        ),
    ]
