# Generated by Django 3.1.2 on 2020-11-11 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battDB', '0161_BaseModelMandatoryName'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvester',
            unique_together={('name', 'user_owner')},
        ),
    ]
