# Generated by Django 3.1.2 on 2020-11-12 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0037_ManufacturingProtocol'),
        ('battDB', '0167_DataRangeType'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='resample',
            field=models.CharField(choices=[('none', 'Do not resample'), ('on_change', 'Sample on change'), ('decimate', 'Take every Nth sample'), ('average', 'Average every Nth sample'), ('max', 'Maximum every Nth sample'), ('min', 'Minimum every Nth sample')], default='none', help_text='Resampling option - TO BE IMPLEMENTED - currently has no effect', max_length=10),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='resample_n',
            field=models.PositiveSmallIntegerField(default=1, help_text='Resampling divisor - TO BE IMPLEMENTED', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='column_name',
            field=models.CharField(default='Ns', max_length=40),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.devicebatch'),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='parameter',
            field=models.ForeignKey(blank=True, help_text='Map this column to a parameter on a device', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfndb.parameter'),
        ),
        migrations.AlterUniqueTogether(
            name='datacolumn',
            unique_together={('device', 'data', 'batch_id'), ('column_name', 'data')},
        ),
    ]
