# Generated by Django 3.1.2 on 2020-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0176_BatchDevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdevice',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional human-readable notes', null=True),
        ),
    ]
