# Generated by Django 3.1.2 on 2020-12-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0201_FilesRefactor3'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdatafile',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='edf',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_data_file', to='battDB.experimentdatafile'),
        ),
    ]
