# Generated by Django 3.1.2 on 2020-12-17 15:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0202_FilesRefactor4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarange',
            name='ts_data',
        ),
        migrations.RemoveField(
            model_name='datarange',
            name='ts_headers',
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='ts_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, editable=False, help_text='Parsed time-series data columns (note: this is bulky data!)', null=True, size=None),
        ),
        migrations.AddField(
            model_name='experimentdatafile',
            name='ts_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, editable=False, help_text='Parsed data column headers', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='config',
            field=models.ForeignKey(blank=True, help_text='All devices in the same experiment must be of the same configuration, i.e. an experiment must use all single cells, or all 2s2p modules, not a mixture of both.', limit_choices_to={'config_type': 'expmt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='battDB.deviceconfig'),
        ),
        migrations.AlterField(
            model_name='experimentdatafile',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Equipment on which this data was recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.equipment'),
        ),
    ]
