# Generated by Django 3.1.2 on 2020-12-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0203_FilesRefactor5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='parse',
        ),
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='parsed_metadata',
        ),
        migrations.RemoveField(
            model_name='experimentdatafile',
            name='use_parser',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='parse',
            field=models.BooleanField(default=False, help_text='Set to True to import data on save'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='parsed_metadata',
            field=models.JSONField(default=dict, editable=False, help_text='metadata automatically extracted from the file'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='use_parser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battDB.parser'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='local_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
