# Generated by Django 3.1.4 on 2020-12-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battDB', '0205_FilesRefactor7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='edf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data_file', to='battDB.experimentdatafile'),
        ),
        migrations.DeleteModel(
            name='Harvester',
        ),
    ]
