# Generated by Django 3.2 on 2021-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='composition',
            field=models.ManyToManyField(help_text='eg. NMC 622 would have 3 Compounds: Nickel 6, Manganese 2, Cobalt 2', through='dfndb.CompositionPart', to='dfndb.Compound'),
        ),
    ]
