# Generated by Django 3.2.7 on 2021-09-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_initial'),
        ('dfndb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='method',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='composition',
            field=models.ManyToManyField(help_text='eg. NMC 622 would have 3 Compounds: Nickel 6, Manganese 2, Cobalt 2', through='dfndb.CompositionPart', to='dfndb.Compound'),
        ),
        migrations.AddField(
            model_name='material',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataparameter',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.data'),
        ),
        migrations.AddField(
            model_name='dataparameter',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dfndb.material'),
        ),
        migrations.AddField(
            model_name='dataparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.parameter'),
        ),
        migrations.AddField(
            model_name='data',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.paper'),
        ),
        migrations.AddField(
            model_name='data',
            name='parameter',
            field=models.ManyToManyField(through='dfndb.DataParameter', to='dfndb.Parameter'),
        ),
        migrations.AddField(
            model_name='data',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together={('name', 'formula')},
        ),
        migrations.AddField(
            model_name='compositionpart',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dfndb.compound'),
        ),
        migrations.AddField(
            model_name='compositionpart',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.material'),
        ),
        migrations.AlterUniqueTogether(
            name='quantityunit',
            unique_together={('quantityName', 'unitSymbol')},
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('symbol', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='dataparameter',
            unique_together={('data', 'parameter', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='compositionpart',
            unique_together={('compound', 'amount', 'material')},
        ),
    ]
