# Generated by Django 3.1.2 on 2020-10-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201008_1430"),
        ("dfndb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="org_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="org_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
        migrations.AddField(
            model_name="method",
            name="org_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="org_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.org",
            ),
        ),
    ]
