# Generated by Django 3.2.2 on 2021-05-11 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(help_text='Chemical formula', max_length=20),
        ),
        migrations.AlterField(
            model_name='compound',
            name='mass',
            field=models.FloatField(default=0, help_text='Optional molar mass, in g/mol', validators=[django.core.validators.MinValueValidator(0, 'Mass cannot be negative!')]),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Full name for the element or compound', max_length=100),
        ),
    ]
