# Generated by Django 3.2.8 on 2021-11-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211115_1357'),
        ('dfndb', '0003_auto_20211011_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='paper',
        ),
        migrations.AddField(
            model_name='data',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.reference'),
        ),
    ]
