# Generated by Django 3.1.2 on 2020-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0003_auto_20201011_1314"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="accepted",),
        migrations.RemoveField(model_name="data", name="org_owner",),
        migrations.RemoveField(model_name="material", name="accepted",),
        migrations.RemoveField(model_name="material", name="org_owner",),
        migrations.RemoveField(model_name="method", name="accepted",),
        migrations.RemoveField(model_name="method", name="org_owner",),
        migrations.RemoveField(model_name="parameter", name="accepted",),
        migrations.RemoveField(model_name="parameter", name="org_owner",),
        migrations.AddField(
            model_name="data",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=20,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=20,
            ),
        ),
        migrations.AddField(
            model_name="method",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=20,
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Draft"),
                    (20, "Submitted"),
                    (30, "Accepted"),
                    (40, "Published"),
                    (50, "Deleted"),
                ],
                default=20,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, help_text="Optional metadata"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="name",
            field=models.CharField(
                help_text="Unique name for this object", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, help_text="Optional metadata"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                help_text="Unique name for this object", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, help_text="Optional metadata"
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="name",
            field=models.CharField(
                help_text="Unique name for this object", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, help_text="Optional metadata"
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=models.CharField(
                help_text="Unique name for this object", max_length=128, unique=True
            ),
        ),
    ]
