# Generated by Django 3.2.7 on 2021-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0003_compound_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('published', 'Published')], default='draft', max_length=16),
        ),
    ]
