# Generated by Django 4.0 on 2021-12-07 12:09

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0004_auto_20211115_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, help_text='Method description in PyBaMM format', max_length=2000), size=None),
        ),
    ]
