# Generated by Django 4.0.2 on 2022-02-16 13:08

from django.db import migrations

from ..initial_units import populate_not_si_quantities, populate_si_quantities


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_initial_data"),
        ("dfndb", "0005_alter_method_description"),
    ]

    operations = [
        migrations.RunPython(populate_si_quantities),
        migrations.RunPython(populate_not_si_quantities),
    ]
