# Generated by Django 4.0.2 on 2022-02-16 15:35

from django.db import migrations

from ..initial_parameters import populate_parameters


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0006_initial_units"),
        ("management", "0003_user_institution")
    ]

    operations = [migrations.RunPython(populate_parameters)]
