# Generated by Django 3.1.2 on 2020-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0007_auto_20201012_2225"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="method",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional human-readable notes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional machine-readable JSON metadata",
            ),
        ),
    ]
