# Generated by Django 4.0.2 on 2022-02-17 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battDB', '0018_alter_devicespecification_config'),
        ('dfndb', '0007_initial_parameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Component',
        ),
    ]
