# Generated by Django 4.0.2 on 2022-02-17 15:32

from django.db import migrations

from ..initial_units import populate_not_si_quantities, populate_si_quantities


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0007_initial_parameters"),
    ]

    operations = [
        migrations.RunPython(populate_si_quantities),
        migrations.RunPython(populate_not_si_quantities),
    ]
