# Generated by Django 3.1.2 on 2020-10-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0008_auto_20201013_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='method',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='created_on',
        ),
    ]
