# Generated by Django 3.2.7 on 2022-02-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0009_add_new_parameters'),
        ('dfndb', '0009_rename_material_compositionpart_component_and_more'),
    ]

    operations = [
    ]
