# Generated by Django 4.0.2 on 2022-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0010_merge_20220218_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='polymer',
            field=models.PositiveIntegerField(default=0, help_text='Degree of polymerisation if this component is a polymer, otherwise 0'),
        ),
    ]
