# Generated by Django 4.1 on 2022-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0011_alter_component_polymer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('device', 'Device'), ('experiment', 'Experiment')], default='device', help_text='Whether this parameter defines a device or is measured in an experiment', max_length=40),
        ),
    ]
