# Generated by Django 4.1 on 2022-08-30 12:17

from django.db import migrations

from ..initial_parameters import set_initial_experiment_parameters


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0012_parameter_parameter_type"),
    ]

    operations = [
        migrations.RunPython(set_initial_experiment_parameters),
    ]
