# Generated by Django 4.1 on 2022-10-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0013_assign_initial_parameters_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Full name for the element or compound.', max_length=100),
        ),
    ]
