# Generated by Django 4.1.3 on 2022-11-25 18:59

from django.db import migrations, models

import dfndb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0014_alter_compound_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='mass',
        ),
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(help_text='Chemical formula', max_length=20, validators=[dfndb.validators.validate_formula]),
        ),
    ]
