# Generated by Django 4.1.3 on 2022-11-29 11:28

from django.db import migrations, models

import dfndb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0015_remove_compound_mass_alter_compound_formula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(help_text='Chemical formula', max_length=20, unique=True, validators=[dfndb.validators.validate_formula]),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(help_text='Full name for the element or compound.', max_length=100, unique=True),
        ),
    ]
