# Generated by Django 3.1.2 on 2020-10-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0015_auto_20201016_1116"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="composition",),
        migrations.DeleteModel(name="CompositionPart",),
    ]
