# Generated by Django 3.1.2 on 2020-10-16 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0019_remove_data_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.data')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfndb.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='parameter',
            field=models.ManyToManyField(through='dfndb.DataParameter', to='dfndb.Parameter'),
        ),
    ]
