# Generated by Django 3.1.2 on 2020-10-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0023_auto_20201016_1219"),
        ("dfndb", "0020_auto_20201016_1211"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="material",),
        migrations.RemoveField(model_name="data", name="type",),
        migrations.RemoveField(model_name="dataparameter", name="amount",),
        migrations.RemoveField(model_name="parameter", name="type",),
        migrations.AddField(
            model_name="dataparameter",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dfndb.material",
            ),
        ),
        migrations.AddField(
            model_name="dataparameter",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "None"), (20, "Input"), (30, "Output")], default=10
            ),
        ),
        migrations.AlterField(
            model_name="data", name="data", field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.paper",
            ),
        ),
    ]
