# Generated by Django 3.1.2 on 2020-10-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0021_auto_20201016_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityunit',
            name='is_SI_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantityunit',
            name='related_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quantityunit',
            name='related_unit',
            field=models.ForeignKey(limit_choices_to={'is_SI_unit': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfndb.quantityunit'),
        ),
    ]
