# Generated by Django 3.1.2 on 2020-10-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0023_auto_20201016_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantityunit",
            name="related_scale",
            field=models.FloatField(
                blank=True, help_text="Scaling of this unit from the SI unit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantityunit",
            name="related_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="If this unit is NOT an SI unit, it should relate to one",
                limit_choices_to={"is_SI_unit": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dfndb.quantityunit",
            ),
        ),
    ]
