# Generated by Django 3.1.2 on 2020-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0028_auto_20201016_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparameter',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
