# Generated by Django 3.1.2 on 2020-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0031_auto_20201019_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="method",
            name="type",
            field=models.IntegerField(
                choices=[(2000, "Experimental"), (1000, "Modelling"), (3000, "Both")]
            ),
        ),
    ]
