# Generated by Django 3.1.2 on 2020-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0032_auto_20201020_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
        migrations.AlterField(
            model_name='method',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(default='autogenerated', editable=False, help_text='Auto-generated unique name, can be used in URLs'),
        ),
    ]
