# Generated by Django 3.1.2 on 2020-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0034_Docstrings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="symbol",
            field=models.CharField(
                help_text="Parameter symbol. Will be decoded as LaTeX", max_length=40
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parameter", unique_together={("symbol", "unit")},
        ),
    ]
