# Generated by Django 3.1.2 on 2020-11-12 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfndb', '0037_ManufacturingProtocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='mass',
            field=models.FloatField(default=0, help_text='optional molar mass', validators=[django.core.validators.MinValueValidator(0, 'Mass cannot be negative!')]),
        ),
    ]
