# Generated by Django 3.1.2 on 2020-11-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0038_auto_20201112_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositionpart",
            name="compound",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="dfndb.compound",
            ),
        ),
    ]
