# Generated by Django 3.1.2 on 2020-12-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfndb", "0039_auto_20201112_1751"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="status",),
        migrations.RemoveField(model_name="material", name="status",),
        migrations.RemoveField(model_name="method", name="status",),
        migrations.RemoveField(model_name="parameter", name="status",),
        migrations.AlterField(
            model_name="parameter",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="dfndb.quantityunit",
            ),
            preserve_default=False,
        ),
    ]
