on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/imperialcollegelondon/faraday-liionsden/liionsden:${{ github.sha }}, docker.pkg.github.com/imperialcollegelondon/faraday-liionsden/liionsden:latest

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v3
        with:
          app-name: "liionsden-prod-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/imperialcollegelondon/faraday-liionsden/liionsden:${{ github.sha }}"
